### ISSUE TITLE
semanage export: global name 'semanage_module_get_version' is not defined

### ISSUE THREAD

**Issue by bachradsusi** [fedora-selinux/selinux#9]
policycoreutils-python-2.4-0.fc23.5.x86_64

    # semanage export -f semanage.mods
    Traceback (most recent call last):
    File "/usr/sbin/semanage", line 856, in <module>
    do_parser()
    File "/usr/sbin/semanage", line 835, in do_parser
    args.func(args)
    File "/usr/sbin/semanage", line 686, in handleExport
    for c in OBJECT.customized():
    File "/usr/lib/python2.7/site-packages/seobject/__init__.py", line 299, in customized
    ALL = self.get_all()
    File "/usr/lib/python2.7/site-packages/seobject/__init__.py", line 295, in get_all
    l.append((semanage_module_get_name(mod), semanage_module_get_version(mod), semanage_module_get_enabled(mod)))
    NameError: global name 'semanage_module_get_version' is not defined

**Comment by bachradsusi** [comment]
The development branch is currently at https://github.com/bachradsusi/selinux/tree/2.4

Builds can be found at plautrba/selinux COPR - https://copr.fedoraproject.org/coprs/plautrba/selinux/

**Comment by bachradsusi** [comment]
Fixed by https://github.com/bachradsusi/selinux/commit/0eb3ecad178187fda63f5ecb0f8f661f87a9647f
